### ISSUE TITLE
Payload size not updated by allocateChunk(WithInfo)

### ISSUE THREAD

**Issue by rex-schilasky** [eclipse/iceoryx#10]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.4.0

**Observed result or behaviour:**
When allocating a chunk with ```allocateChunk``` or ```allocateChunkWithInfo``` using the dynamic payload option (```useDynamicPayloadSizes = true```) the ```ChunkInfo``` field ```m_payloadSize``` is initialized correctly by the first call. Subsequent calls of the same function with an increased ```payloadSize``` do not update the member variable.

**Expected result or behaviour:**
```ChunkInfo::m_payloadSize``` should reflect the current payload size under all conditions.

**Conditions where it occurred / Performed steps:**
```cpp
// publisher side
auto ci = m_publisher->allocateChunkWithInfo(42, true);
m_publisher->sendChunkWithInfo(ci);

auto ci = m_publisher->allocateChunkWithInfo(42+1, true);
m_publisher->sendChunkWithInfo(ci);

...

// subscriber side
const iox::mepoo::ChunkInfo* ci(nullptr);
while (m_subscriber->getChunkWithInfo(&ci))
{
  std::cout << ci->m_payloadSize << std::endl;
  m_subscriber->releaseChunkWithInfo(ci);
}
```

**Comment by michael-poehnl** [comment]
Thanks @rex-schilasky. We have an optimization to recycle the last chunk that was sent if this one is free again. As we don't create a new chunk it is not initialized again. So we must check if the old chunk can really be used again and update its payload size

**Comment by rex-schilasky** [comment]
Thank you for fixing that !
