### ISSUE TITLE
Need for easy mempool configuration

### ISSUE THREAD

**Issue by Karsten1987** [eclipse/iceoryx#13]
## Brief feature description

Motivated from https://github.com/ros2/rmw_iceoryx/issues/5

## Detailed information

The current mempool configuration is hardcoded in https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/source/mepoo/mepoo_config.cpp#L44-L54 and should be changed to be set dynamically on startup.

**Comment by mossmaurice** [comment]
Hi @Karsten1987,

thanks for your feature request. Having a hard-coded compile-time mempool config is quite unpleasant. The feature "run-time config file for RouDi" is definitely on our roadmap (see 2nd point in https://github.com/eclipse/iceoryx/blob/master/PLANNED_FEATURES.md). You can expect it to arrive in Q1 2020.

Simon

**Comment by michael-poehnl** [comment]
work on that just started

**Comment by elBoberido** [comment]
it's almost ready. expect a pull request within the next days

**Comment by Karsten1987** [comment]
Is there any update on this? #12 also seems to be in need for this.

**Comment by michael-poehnl** [comment]
#38
