### ISSUE TITLE
Naming convention for iceoryx binaries

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#147]
## Brief feature description

Iceoryx exports multiple binaries. Should there be a naming convention for them ? If yes, what should this be ?

**Comment by ithier** [comment]
Currently, we have the following binaries:
- gateway_dds2iceoryx
- gateway_iceoryx2dds
- iceoryx_introspection_client
- iceperf-hardy
- iceperf-laurel
- ice-publisher-bare-metal
- ice-publisher-simple
- ice-subscriber-bare-metal
- ice-subscriber-simple
- RouDi

Suggestion: streamline naming to follow the following convention: `iox-${application_name}`

**Comment by elBoberido** [comment]
so we would have something like
- iox-roudi
- iox-gw-dds2iceoryx
- iox-gw-iceoryx2dds
- etc.
I like that.
I'm not sure if we should also do it for our examples or just for binaries we would distribute in a release

**Comment by ithier** [comment]
I would vote to use it for all of them for consistency... I like the idea of being able to just type in my terminal: `iox- <tab> <tab>` and to easily see the list of iceoryx applications.

I am not too fussed though, if there is a strong want/need to break the convention for examples then we can leave them as is.

**Comment by elBoberido** [comment]
I also don't have strong feelings about this. We should maybe use something like an `iox-ex-` prefix.
@MatthiasKillat, what's your opinion regarding a prefix for examples? I know we had a discussion in the past regarding something similar.
