### ISSUE TITLE
File-based Configuration for DDS Gateways

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#148]
## Brief feature description

Enable the services to be forwarded via DDS gateways via a Toml configuration rather than needing to be dynamically discovered.

## Detailed information

Pros:
* Quicker setup time
* Lower the chance of missing data points

**Comment by ithier** [comment]
Forgot to mention - this is required for the dds gateway using cyclonedds as dds service discovery is not implemented there.

**Comment by budrus** [comment]
So this is the workaround for https://github.com/eclipse-cyclonedds/cyclonedds/issues/42

**Comment by ithier** [comment]
This issue was resolved in #162.
