### ISSUE TITLE
Docker environment for building and running iceoryx and examples.

### ISSUE THREAD

**Issue by Mr-Slippery** [eclipse/iceoryx#15]
## Brief feature description

A Docker environment allows reproducible builds with controlled dependencies without polluting the user's host machine with extra packages needed for building and running iceoryx applications.

Acceptance criteria:
1. create a Docker image with a built iceoryx library, RouDi daemon, and examples. 
2. provide an easy way to launch and use containers based on the above image.

A related follow-up may be publishing the Docker image to Docker Hub to allow users to run the prebuilt image directly, but this should be decided by the core iceoryx team.

## Detailed information

Proposed content in `tools/docker` is:
- Dockerfile
- build/launch script(s)
- README.md
- other needed configuration files

**Comment by mossmaurice** [comment]
Hi @Mr-Slippery 
thanks for your feature request and your related pull request! We're currently in the process of setting up a Jenkins (https://ci.eclipse.org/iceoryx) and we'd like to use this docker image there. We might be using DockerHub at a later stage.

**Comment by Mr-Slippery** [comment]
Thanks for considering the issue and for the pull request reviews!
Everything is merged, so closing the issue, thanks again.
