### ISSUE TITLE
There is no ./build/iceoryx_examples/icedelivery/ice_sender and ./build/iceoryx_examples/icedelivery/ice_receiver

### ISSUE THREAD

**Issue by zzzzzzli** [eclipse/iceoryx#156]
## Required information

**Operating system:**
Ubuntu 18.04

**Compiler version:**
E.g. gcc 7.5.0

**Observed result or behaviour:**
the console output `bash: ./build/iceoryx_examples/icedelivery/ice_sender: No such file or directory` when I run `docker exec -it roudi /bin/bash`,before that, I installed iceoryx using the command `./tools/docker/build_and_run.sh`  and I replace the source image ubuntu:bionic to ubuntu:18.04 in the dockerfile, and add the options `build-test clean release` after the command `./tools/iceoryx_build_test.sh` .

Additionally, when I install iceoryx with command `./tools/docker/build_and_run.sh` with `./tools/iceoryx_build_test.sh` options `test clean release`, it shows many errors during run tests.

**Expected result or behaviour:**
What do you expect to happen?
As the [README.md](https://github.com/eclipse/iceoryx/tree/master/tools/docker) shows:
```
Sending: 0
Sending: 1
Sending: 2
Sending: 3
```
**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.
Each time

**Comment by elfenpiff** [comment]
@zzzzzzli Thank you for your report! It seems that we did not keep track of our docker documentation when we updated the file names of our icedelivery example. We updated the documentation and when the pull request https://github.com/eclipse/iceoryx/pull/159 is merged the documentation should be correct again.

In the meantime you can replace the path to the sender with: `./build/iceoryx_examples/icedelivery/ice-publisher-simple` and the receiver is located at `./build/iceoryx_examples/icedelivery/ice-subscriber-simple`.

**Comment by zzzzzzli** [comment]
Thank you very much.
