### ISSUE TITLE
cxx::optional and cxx::expected adjustments

### ISSUE THREAD

**Issue by elfenpiff** [eclipse/iceoryx#160]
## Brief feature description

- The methods of `cxx::expected` `on_success` and `on_error` should be renamed to `and_then` and `or_else`.
- It should be possible to create an `cxx::optional` directly from an `cxx::expected` with a method called `.to_optional()` which returns the value of the `cxx::expected` packed inside an `cxx:optional` if it contains a value otherwise it returns the `cxx::nullopt`
- If a value is moved outside the `cxx::optional` the method `has_value` should no longer return true since we would like to avoid undefined behavior
```
cxx::optional<int> a = 5;
if ( a.has_value() ); // returns true
int b = std::move(*a);
if ( a.has_value() ); // should now return false since the value is moved outside the optional

// this case would false assume that the optional has no more contained value but at the moment I do not see a problem with that.
std::move(*a);
```
- If a value is moved outside the `cxx::expected` it should no longer be contained. We need the methods `has_value()` and `has_error()` which both should return false in that case. If the methods `and_then()` or `or_else()` are called on an `cxx::expected` in that state they should terminate.

## Detailed information

We would further reduce undefined behavior.

**Comment by elfenpiff** [comment]
@elBoberido  sadly it is not possible to invalidate an optional when the value is moved out since
`int b = std::move(*a);` calls the dereferencing operator which returns `T&` and the `std::move` is transforming it into an rvalue. This could only be done for the method `T&& value() &&` but then it would be inconsistent in the behavior.

**Comment by dkroenke** [comment]
Would you please create a link to the according C++ standards where the adjustments are based on. That makes comparing easier.
