### ISSUE TITLE
Dangling pointer/chunks in the introspection app

### ISSUE THREAD

**Issue by elBoberido** [eclipse/iceoryx#197]
## Required information

**Operating system:**
All

**Compiler version:**
All

**Observed result or behaviour:**
A raw pointer to the payload of a chunk is stored in a std::dequeu and then the chunk is released. This results in a dangling pointer to a chunk.
e.g. https://github.com/eclipse/iceoryx/blob/master/tools/introspection/source/introspection_app.cpp#L713
The same applies to the other introspection topics

**Expected result or behaviour:**
Instead of the pointer, the chunk should be stored in the std::dequeu.

**Comment by pabloEnzes** [comment]
---
 tools/introspection/source/introspection_app.cpp | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/tools/introspection/source/introspection_app.cpp b/tools/introspection/source/introspection_app.cpp
index 6325f3f..f35ac8b 100644
--- a/tools/introspection/source/introspection_app.cpp
+++ b/tools/introspection/source/introspection_app.cpp
@@ -710,7 +710,6 @@ void IntrospectionApp::runIntrospection(const iox::units::Duration updatePeriodM
                 decltype(mempoolSamples)::value_type typedMempoolSample =
                     static_cast<decltype(mempoolSamples)::value_type>(rawMempoolSample);
                 mempoolSamples.push_back(std::move(typedMempoolSample));
-                memPoolSubscriber.releaseChunk(rawMempoolSample);
             }
 
             if (mempoolSamples.empty())
@@ -738,6 +737,11 @@ void IntrospectionApp::runIntrospection(const iox::units::Duration updatePeriodM
                 std::for_each(
                     currentIter, mempoolSamples.end(), [&](decltype(*it) samplePtr) { printMemPoolInfo(*samplePtr); });
             }
+            for(auto& sample: mempoolSamples)
+            {
+            	memPoolSubscriber.releaseChunk(sample);
+            }
+            mempoolSamples.clear();
         }
 
         // print process information
--

**Comment by elBoberido** [comment]
Hi pabloEnzes,

yes, that's a viable fix for the problem. For the mempools it's will be fixed by #211 

You could create a fix for the other introspection topics. To be able to include your fix, you need to sign the eclipse contributor agreement. See also here https://github.com/eclipse/iceoryx/blob/master/CONTRIBUTING.md

We are looking forward to your contributions.

**Comment by elBoberido** [comment]
This was fixed by #211. The other introspection topics did not have this problem, since they were not cached in the first place.
