### ISSUE TITLE
dds_gateway build error

### ISSUE THREAD

**Issue by dolmens** [eclipse/iceoryx#209]
ubuntu 18,04
commit: 8995625153cb49163fc70e5b5746cf7486690557
cmake -Bbuild -Hiceoryx_meta -DTOML_CONFIG=ON -Ddds_gateway=ON

toml_gateway_config_parser.hpp:22:10: fatal error: cpptoml.h: No such file or directory

**Comment by dolmens** [comment]
I guess it is a bug in dds_gateway cmake, posh build successfully.

**Comment by ithier** [comment]
I'm not able to reproduce your error.

It seems that for some reason cpptoml is not being fetched / found properly.
Is cpptoml.h present in `build/dependencies/install/include` ?
What do the cmake logs say to about fetching cpptoml when you run `cmake -Bbuild -Hiceoryx_meta -DTOML_CONFIG=ON -Ddds_gateway=ON` ? The first thing it should do is fetch cpptoml.

Alternatively, have you tried using the script `tools/iceoryx_build_test.sh` ?
You should be able to build with simply: `./tools/iceoryx_build_test.sh release with-dds-gateway`

**Comment by dolmens** [comment]
@ithier cpptoml.h is in the proper directory. I finnaly surpassed this by modifying the iceoryx_dds/CMakeLists.txt to add target_link_libraries cpptoml to the target iceoryx_dds and others.

**Comment by ithier** [comment]
That's strange given cpptoml is a header-only library.

**Comment by mossmaurice** [comment]
@dolmens Can I close this issue?

**Comment by ithier** [comment]
Unable to reproduce.
