### ISSUE TITLE
Availability of code coverage reports

### ISSUE THREAD

**Issue by bishibashiB** [eclipse/iceoryx#217]
## Brief feature description
Extending iceoryx CI to include (free github action on) code coverage
 
Github actions offer not only the build and test verification but also code coverage visualizations. Few services are available (usually free for OSS repos) and would support PR reviews. 
This issue is meant to start a discussion / collect ideas.

## Detailed information
Although available coverage tools (rule sets) might not match the target goals for e.g. MC/DC coverage, still they offer an early feedback / check on coverage of a PR by just adding an additional github workflow (*.yml).
Example is available on this [fork branch](https://github.com/bishibashiB/iceoryx/tree/feature/codecov_action)  utilizing a codecov github action. Report for this example is [here](https://codecov.io/gh/bishibashiB/iceoryx/branch/feature%2Fcodecov_action). 
Early tooling will have to be replaced or extended at a later point (new rule sets). In the meanwhile code coverage / quality can already be tracked.

**Comment by dkroenke** [comment]
codecov report available and the developer can fetch his own local reports
