### ISSUE TITLE
Extend compile failure tests

### ISSUE THREAD

**Issue by mossmaurice** [eclipse/iceoryx#222]
## Brief feature description

Create compile failure tests for all classes which have deleted c'tors/assignment operators (comes from #202)

@elBoberido please extend this list if you have more ideas.

**Comment by elBoberido** [comment]
this is dependent on #213

**Comment by mossmaurice** [comment]
> 
> 
> since this is dependent on #213, do we really need this for 1.0

Thanks for the hint, removed it.

**Comment by mossmaurice** [comment]
Move content to #213, closing this one.
