### ISSUE TITLE
cxx::vector::erase() should return an iterator following the last removed element

### ISSUE THREAD

**Issue by elfenpiff** [eclipse/iceoryx#226]
## Brief feature description

The `std::vector::erase()` method returns an iterator following the last removed element. We should be compatible in this aspect to the STL.

**Comment by bishibashiB** [comment]
side note: 
also check call to destructor in `std::vector::erase()` being called on removed list element (not last/'back' element) of vector.

**Comment by mossmaurice** [comment]
@bishibashiB Can we close this issue?

**Comment by bishibashiB** [comment]
Only cosmetic things addressed (left) => closing is fine with me. 
Thanks bothering~
