### ISSUE TITLE
Version check for RouDi and apps

### ISSUE THREAD

**Issue by sculpordwarf** [eclipse/iceoryx#229]
## Brief feature description
Ensure the iceoryx user is building the apps and RouDi with the same versions e.g. can't use different mixed builds

## Detailed information
Check build version from RouDi against the apps ones
over-writeable with a RouDi startup parameter via console

**Comment by dkroenke** [comment]
@sculpordwarf this is a duplicate from https://github.com/eclipse/iceoryx/issues/228
