### ISSUE TITLE
Segmentation Fault in Posix Timer

### ISSUE THREAD

**Issue by elfenpiff** [eclipse/iceoryx#243]
## Required information

**Operating system:**
Ubuntu 18.04 LTS, Archlinux

**Compiler version:**
GCC 7.4.0, CLANG 10.0, GCC 10.2

**Observed result or behaviour:**
The now disabled unit test: `Timer_test.SelfTriggeringTimerWorksAndDoesNotCauseSegFault` seg faults

**Expected result or behaviour:**
The unit does not seg fault

**Comment by shankar-in** [comment]
@elfenpiff could you pls let me know if this seg fault issue is fixed? Still the test looks disabled `DISABLED_SelfTriggeringTimerWorksAndDoesNotCauseSegFault`

**Comment by elfenpiff** [comment]
@shankar-in the issue seems to be solved.

**Comment by shankar-in** [comment]
@shankar-in Okay I will enable the test again.
