### ISSUE TITLE
Update Googletest to v1.10.x

### ISSUE THREAD

**Issue by bishibashiB** [eclipse/iceoryx#246]
## Brief feature description
Current test framework bases on Googletest v1.8.1 which was superseded by v1.10.0 (~10/2019).

## Detailed information
There are improvements to mock_method as well as renaming in test macros:
[https://github.com/google/googletest/releases](https://github.com/google/googletest/releases) 
IMO it will be beneficial to update, so that new test cases can be written according to the new macro names.

**Comment by mossmaurice** [comment]
As described in our [CONTRIBUTING.md](https://github.com/eclipse/iceoryx/blob/master/CONTRIBUTING.md#testing), we currently require v1.8.1. AFAIK this has not changed as some tools depend on this version :-(
What about discussing this as part of #217? It highly depens on the tools being used.

**Comment by dkroenke** [comment]
For safety we need to use a fixed gtest version to have a consistent tool support and classification/certification. Therefore we currently stay at this version.
