### ISSUE TITLE
Name clash in RouDi process removeProcess()

### ISSUE THREAD

**Issue by marthtz** [eclipse/iceoryx#271]
## Required information

**Operating system:**
General issue

**Compiler version:**
General issue

**Observed result or behaviour:**
PR #258 cleaned-up some local variable name prefixes. However, that introduced a name clash inside a function rendering a check useless.

**Expected result or behaviour:**
Do a proper check.

**Conditions where it occurred / Performed steps:**
In file `/iceoryx_posh/source/roudi/roudi_process.cpp` inside `bool ProcessManager::removeProcess(...)` fix
```
...
auto name = it->getName();
if (name == name)
...
```

**Comment by elBoberido** [comment]
Good catch. I hoped `-Wtautological-compare` could help here, but it seems it doesn't catch it

**Comment by marthtz** [comment]
> 
> Good catch. I hoped `-Wtautological-compare` could help here, but it seems it doesn't catch it
Yeah, unfortunately it doesn't. Checked it.
