### ISSUE TITLE
Introduce API IsEnabled(LogLevel logLevel) in Logger

### ISSUE THREAD

**Issue by prasannabhat** [eclipse/iceoryx#278]
## Brief feature description

Introduce API `IsEnabled(LogLevel logLevel)` in Logger

## Detailed information

This API checks current configured log reporting level.
Applications may want to check the actual configured reporting log level of certain loggers before doing log data preparation that is runtime intensive.

**Comment by ithier** [comment]
@dkroenke @prasannabhat Can this be closed ?

**Comment by prasannabhat** [comment]
@ithier It can be closed
Here is the  [PR](https://github.com/eclipse/iceoryx/pull/309)
Not sure why its not linked to the issue (commits and branch name have issue no)
