### ISSUE TITLE
Full IceOryx Public API Cheat Sheet

### ISSUE THREAD

**Issue by elfenpiff** [eclipse/iceoryx#283]
## Brief feature description

We require a cheat sheet which provides a quick and complete overview over all IceOryx features from a use case point of view.
This cheat sheet should come with an example which uses all those features.

- [ ] Update CMake Docu and check for consistency
- [ ] Explain cmake options in detail
- [ ] Explain the ideas, concept of `optional` and `expected`
- [ ] Update icedelivery documentation to new API

**Comment by MatthiasKillat** [comment]
I do think explaining optional and expected in detail belongs elsewhere, but I will include a short description. We already have one for expected in error-handling.md, I will link that I guess.

We need to consolidate our documentation, but this belongs to a different issue (which may be worth creating). This should be done for 1.0 but not 0.9.

**Comment by MatthiasKillat** [comment]
cmake options belongs to the installation guide. 

@after discussion with @mossmaurice  we redefined the goal of this issue as follows.
1) Create a document  to get the user started to use iceoryx. This includes explaining the necessary concepts and terminology from an application developer side to understand the examples (some terminology). This does not include details about e.g. shared memory and zero copy communication, as this is not needed by an application developer.

2) Remove inconsistencies with other documents as far as possible (e.g. the icedelivery example readme is severely outdated). 
Adapt the icedelivery readme to reflect the new modern API.

3) Installation and cmake guide is out of scope

We will need to consolidate the documentation and create a documentation concept/structure for the 1.0 release. This is out of scope here and may warrant a separate issue.
