### ISSUE TITLE
Stable version required

### ISSUE THREAD

**Issue by MiaoDX** [eclipse/iceoryx#287]
## Brief feature description

Stable version for upstream applications and QNX support.

## Detailed information

Hi, thanks for your kindly open-sourced solution, this seems promising. I notice that this project is under heavy code review and improvement recently, so when shall I consider this as one stable component for my projects, and will 1.x be around the corner?

And one more thing, I tried to build on QNX platform, and it succeeds at the compiling phase but failed to execute, the output looks strange.

``` vi
/iox-roudi 
1970-01-20 02:24:51.494 [ Info  ]: No config file provided and also not found at '/etc/iceoryx/roudi_config.toml'. Falling back to built-in config.
Log level set to: [Warning]
xxx/iceoryx/iceoryx_utils/source/posix_wrapper/message_queue.cpp:129 { static iox::cxx::expected<bool, iox::posix::IpcChannelError> iox::posix::MessageQueue::unlinkIfExists(const string&) }  :::  [ 89 ]  Function not implemented
```

**Comment by elBoberido** [comment]
@MiaoDX regarding the QNX issue, the posix message queue is not available by default so you have to start `mqueue` manually

I think @budrus can tell you more about the 1.x release. At least a stable API is around the corner, probably in October. If we do not encounter severe issues with that API after the initial release, we will keep it stable, regardless if it's a 1.x release or not

**Comment by budrus** [comment]
Thanks for the question @MiaoDX. Indeed, 1.0.0 is around the corner. 
We will break the API in the next weeks, [0.17.0](https://github.com/eclipse/iceoryx/tree/v0.17.0) is the last version with the old API. We already heavily work on the new API and new features like a C API, a waitset and history QoS. I guess we first introduce the new API on probation and start using it. When it feels stable and good we will do the 1.0.0 release with long-term support. 

Check our [ gitter channel ]([url](https://gitter.im/eclipse/iceoryx)) for updates

**Comment by MiaoDX** [comment]
Yeah, looking forward to that ~
Currently, we are using hand-crafted cpp11+atomic ptr+move operation for single producer and single consumer scenario, the singleprocess demo does seem promising, and once QNX+Linux is all-well tested, I'd like to try out.
