### ISSUE TITLE
Colliding filenames within .github folder

### ISSUE THREAD

**Issue by Karsten1987** [eclipse/iceoryx#29]
## Required information

**Operating system:**
Any case insensitive filesystem

When checking out (on OSX):
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '.github/ISSUE_TEMPLATE/BUG_REPORT.md'
  '.github/ISSUE_TEMPLATE/bug_report.md'
  '.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md'
  '.github/ISSUE_TEMPLATE/feature_request.md'
```

Is that simply a typo or why are these files existing with different cases?

**Comment by mossmaurice** [comment]
Thanks @Karsten1987 for reporting this issue.

With this Bugzilla ticket (https://bugs.eclipse.org/bugs/show_bug.cgi?id=552491) the lower case files were introduced. @eclipsewebmaster Could you please remove the duplicate files that are not used by the Github Web GUI? Unfortunately I can't check it myself as Eclipse committers don't have access to this feature.

**Comment by mossmaurice** [comment]
Today I learned: Github shows that a file is currently used as an issue template ("This file is used as an issue template."). Will remove the duplicate files.
