### ISSUE TITLE
Consistency between cxx::optional and cxx::expected APIs

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#297]
## Brief feature description
The two APIs are inconsistent when it comes to retrieving their stored value.
It's a bit annoying when using them both for development.

## Detailed information
Get value from `cxx::expected`: `expected.get_value()`
Get value from `cxx::optional`: `optional.value()`

I don't have a preference for either, just for consistency :stuck_out_tongue:.

**Comment by elBoberido** [comment]
Did you have a look at the proposal of std::expected?
Personally I would vote for `value()` ;)

**Comment by elfenpiff** [comment]
> Did you have a look at the proposal of std::expected?
> Personally I would vote for `value()` ;)

Me too!
