### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by mossmaurice** [eclipse/iceoryx#3]
Required information

**Operating system:** Ubuntu 18.04 LTS

**Compiler version:** GCC 7.4.0

**Observed result or behaviour:**

- Debian release link does not work
- Example links $ROOT/README.md broken (e.g. **examples**/icedelivery)
- Typo in $ROOT/README.md "Great that **your** still here"
- Typo in $ROOT/README.md "./tools/iceoryx_build **-** test.sh"
- Mention examples are built by script in $ROOT/iceoryx_examples/README.md 

**Expected result or behaviour:** No wrong script names, links or typos

**Conditions where it occurred / Performed steps:** Github web GUI (Commit e5c23eaf5c351ef0095e43673282867b8d060026)

**Comment by michael-poehnl** [comment]
#4
