### ISSUE TITLE
On the Road to 1.0

### ISSUE THREAD

**Issue by elBoberido** [eclipse/iceoryx#305]
## Brief feature description

This is a tracking issue for our 1.0 release.

## Detailed information

Required features/strategies for our 1.0 release.

- [x] N:M communication #25
- [x] new Publisher/Subscriber API #218

Postponed to 2.0

- [ ] ...

**Comment by elBoberido** [comment]
Please add stuff you think should go into our 1.0 release in the comment section. Vote by the 👍 and 👎 if you want the idea into 1.0

**Comment by elBoberido** [comment]
I think the API compliance tests should be ready for the 1.0 release
#284

**Comment by elBoberido** [comment]
Building blocks should also be finished, at least the mandatory ones from #252

**Comment by elBoberido** [comment]
iceoryx-posh and iceoryx-utils meet [ROS Quality Level](https://github.com/ros-infrastructure/rep/blob/master/rep-2004.rst) 1 for Linux/Mac/Windows (maybe Level 2?)

**Comment by elBoberido** [comment]
Rework non-shm interprocess communicution
- rework the initial registering at RouDi, and make sure an application always get a response, at least an error response, even if the application is build with an incompatible iceoryx version compared to RouDi 
- document the serialization and/or refactor the current one
- don't transmit the response deep down in multiple classes, but let the classes just return their response to the caller, which makes testing easier

**Comment by elBoberido** [comment]
decide if we use C++14 as standard (#220)

**Comment by elBoberido** [comment]
detect if an application registers at RouDi is build with an incompatible iceoryx version compared to RouDi

**Comment by budrus** [comment]
see https://github.com/eclipse/iceoryx/projects/2 for content of 1.0 release
