### ISSUE TITLE
RouDi segfault in introspection mempool port

### ISSUE THREAD

**Issue by dkroenke** [eclipse/iceoryx#314]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.5.0

**Observed result or behaviour:**
When starting RouDi, some applications and the Introspection. An error in RouDi comes up:
[ Error ]: There is no shared memory available to allocate from! Terminating!

The mempool receiver fifo in introspection is higher as the mempool configs.

**Expected result or behaviour:**
RouDi shall not terminate when starting the introspection

**Conditions where it occurred / Performed steps:**
When starting RouDi, some applications and the Introspection.

**Comment by marthtz** [comment]
Duplicate of #322
