### ISSUE TITLE
iceoryx_mgmt occupying 82MB space. Can we reduce it?

### ISSUE THREAD

**Issue by Indra5196** [eclipse/iceoryx#318]
![Capture](https://user-images.githubusercontent.com/34583762/94295952-adcc5380-ff7f-11ea-994e-446ae610984a.PNG)
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

iceoryx_mgmt occupies approximately 82MB space. Can it be reduced? If yes, How? if no, Why?

**Conditions where it occurred / Performed steps:**
Simply run the RouDi executable.

**Comment by budrus** [comment]
Yes you can. We are using fixed size containers in the management segment as we are not using dynamic memory allocation during runtime. There is a default configuration which fits more to larger systems. Besides the memory pool configuration you can change these compile time constants. Check here [here](https://github.com/eclipse/iceoryx/blob/master/doc/installation-guide.md#build-with-cmake) what you can change via CMake switch. Especially the constants for publishers and subscribers are currently relevant   

The maximum power you have if you directly check the constants in [posh_types](https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp). But the ones available as CMake switch should be the most interesting ones

**Comment by budrus** [comment]
@Indra5196, did it work out? I would close this issue if you think the questions are answered
