### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by budrus** [eclipse/iceoryx#32]
## Brief feature description

Having the possibility to use iceoryx on macOS

## Detailed information

Needed for ROS2 tier 1 support
[ROS2 Tiers](https://www.ros.org/reps/rep-2000.html#support-tiers)

**Comment by marthtz** [comment]
Tasks for macOS support:
- [ ] ACL needs to be adapted to macOS
- [ ] Semaphore `sem_timedwait()` not available and needs to be created
- [ ] Implement new OS timer based on "dispatch source"
- [ ] Replace message queues with socket communication
- [ ] Replace or find appropriate RT library if necessary
- [ ] Modify `pthread_setname_np()` calls
- [ ] Resolve type conflicts for `cxx::align` in
  - `requiredManagementMemorySize()`
  - `requiredManagementMemorySize()`
  - `requiredManagementMemorySize()`
  - `Allocator::allocate()`
- [ ] Resolve type conflict for `gid_t` in `PosixUser::getGroups()`
- [ ] Resolve type conflict for `wprintw()` in `printProcessIntrospectionData()`

**Comment by michael-poehnl** [comment]
I guess we start without acl or a replacement for it. Having different access groups on macOS is low prio

**Comment by elfenpiff** [comment]
Mac OS works!
