### ISSUE TITLE
Simplify API for "expected optionals"

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#340]
## Brief feature description
The current API for expected optionals is a little convoluted, requiring many layers of "unwrapping" before the data can finally be accessed.

## Detailed information
We have this API:
```
    auto result = cxx::expected<cxx::optional<ValueType>>();
    if(!result.has_error())
    {
        auto optional = result.get_value();
        if(optional.has_value())
        {
            auto value = optional.value();
            // What did I want to do again ?
        }
    }
```
And this one (loaning a sample from a publisher):
```
    TypedPublisher<ValueType> typedPublisher{"service", "instance", "event"};
    result = typedPublisher.loan().and_then([](cxx::optional<ValueType> optional){
        if(optional.has_value())
        {
            auto value = optional.value();
            // Now I can finally play the game !
        }
    })
```

These steps are a little tedious to need to go through and can be a little confusing for newcomers.

**Comment by budrus** [comment]
I'm wondering if we need a new issue for this topic or if this is just another pull request for #252 
As this is relevant for 1.0 you would have to assign it to this project etc. Now it is a new issue that is not assigned

**Comment by ithier** [comment]
Adding additional "todo" items within another issue is not great for visibility.
Also, I'm not sure if "creating an issue per feature" fits the github workflow (but I am no expect). 
For example, what happens if a user would like to raise an issue ?

**Comment by budrus** [comment]
It is about issue granularity I guess. And this has currently a wide range. If there is an issue for "Write a new C++ API" and another issue for "improve this specific aspect of the not yet finalized C++ API", I have the feeling that it should be nested but with the single layer of issues they are side by side. Too heterogeneous for me. Sure a user can raise whatever issue but if we implement new features we should have some best practise.

**Comment by ithier** [comment]
My preference would be to have higher granularity issues, i.e. in the "improve this specific aspect of the not yet finalized C++ API" form, and then group these using milestones.
We should definitely have a consensus though.

**Comment by ithier** [comment]
I have a working prototype that might fix this problem.
Behold:
```
subscriber->take()
       .and_then([](iox::popo::Sample<const Position>& position){
            std::cout << "Got value: (" << position->x << ", " << position->y << ", " << position->z << ")" << std::endl;
        })
        .if_empty([]{
            std::cout << "Didn't get a value, but do something anyway." << std::endl;
        });
```

The expected has a specialization for when its type is an optional.
In this case it will:
* automatically retrieve the value from the optional when it is not empty
* provide an additional method where the user can provide a lambda for the case when the optional is empty

I have this working already, it just builds on the code introduced in #335 so I need to wait for this to be merged before I can open the PR.

Thoughts ? @budrus @elBoberido @elfenpiff @mossmaurice

**Comment by budrus** [comment]
Cool @ithier. This is an extension for the expected and not a special solution for the subscriber take or the Sample class, right?

How would the error handling be done? Can you extend your sample code?

**Comment by ithier** [comment]
Yes you can still tack on an `or_else()` at the end to catch the error.
I will update the snippet.

**Comment by elBoberido** [comment]
I like it way more than the idea with the `ReceivedSample` and even a little more than the pragmatic approach to omit the optional and encode the nullopt case into an error code. It's like de-referencing to the lowest value. 

I'm just a bit hesitant if it's not a bit too nifty and makes things a bit inconsistent when the non-functional approach is used.
What does `get_value()` return, the optional or the value of the optional? If `has_value()` returns `false`, it doesn't mean that `has_error()` returns `true`, right?

If you look at Rust, they are able to solve this problem quite elegant with the `?` operator, but they have a `flatten` method for nested `Option` and `Result`, so a `Option<Option<T>>` becomes a `Option<T>`. It's a different Problem than we have and I'm also not quite sure if I like the idea, so consider this just as food for thought. What do you think about also having this `flatten` method? After calling `flatten` you gain access to the functions/semantics you introduced, including for `has_value()`, etc.
