### ISSUE TITLE
cxx::expected's bool operator should return has_value()

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#351]
## Required information
**Observed result or behaviour:**
Currently, the boolean operator of `cxx::expected` returns `has_error()`.

**Expected result or behaviour:**
According to [the proposal](https://raw.githubusercontent.com/viboes/std-make/master/doc/proposal/expected/DXXXXR0_expected.pdf) (pg. 23), it should return `has_value()`.

**Comment by budrus** [comment]
I guess this was already merged with #297. Right @ithier ?
