### ISSUE TITLE
Update maintainer list

### ISSUE THREAD

**Issue by elBoberido** [eclipse/iceoryx#366]
## Brief feature description

The email addresses of some maintainer are outdated and some maintainer are missing. Instead of listing them explicitly, add a link to https://projects.eclipse.org/projects/technology.iceoryx/who

**Comment by budrus** [comment]
I was wondering if we should remove this completely. We have the gitter channel etc. if people want to get in touch with us

**Comment by elBoberido** [comment]
I'm for it. Do we still need a list of maintainer, without email addresses?

**Comment by mossmaurice** [comment]
Adding a link to the Eclipse committer page is a great idea.
