### ISSUE TITLE
create multi publisher example

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse/iceoryx#394]
## Brief feature description

With the resize feature #216 we will enable sending from multiple publishers to a single receiver. We need asuitable example to demonstrate this.

## Detailed information

Create an example demonstrating the multi publisher use case, thereby verifying (in addition to the existing tests) that this use case works properly. It is also possible to adapt an existing example, but this should probably be avoided to keep the basic use case separated from advanced use cases.

This also serves as a further test of the usability of the new API.

**Comment by budrus** [comment]
I'm wondering if we should extend the new modern cpp icedelivery example. If you can provide via command line parameter something like an ID that is appended to the Runtime name it would already be done. I guess with the ROS2 demo nodes you can also have n:m pub sub just by starting new instances of chatter publishers and subscribers. 

I tried iceoryx n:m communication already with dirty local changes in the modern cpp example, it worked fine
