### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sirinath** [eclipse/iceoryx#412]
Can support for MS Windows be added.

**Comment by dkroenke** [comment]
Hello @sirinath,
thanks for your request, we have already addressed it in https://github.com/eclipse/iceoryx/issues/33 for ROS 2 Tier1 support. Basic parts of iceoryx are already compiling in the CI pipeline https://github.com/eclipse/iceoryx/runs/1516885020

**Comment by elfenpiff** [comment]
@sirinath I also would like to have Windows support but sadly it is postponed. We pursue it at the moment with lower priority but we are still aiming for it for the 1.0 release: https://github.com/eclipse/iceoryx/milestone/3 , see Windows 10 support

**Comment by dkroenke** [comment]
@sirinath I will close this issue because it is a duplicate.
