### ISSUE TITLE
Iceoryx shared memory between docker containers (and host system)

### ISSUE THREAD

**Issue by jeising** [eclipse/iceoryx#42]
## Brief feature description

To communicate between docker containers and their applications using shared memory, `RouDi` and `/dev/shm/`-locations need to be shared across these containers. This would allow proper separation of applications while using highly performant shared memory between them.

## Detailed information

My initial try was to mount:
- `/dev/shm/iceoryx_mgmt`
- `/dev/shm/[group-name]`
- and `var/run/roudi.pid`

While starting RouDi on the host system, in the docker container I could see the mounted locations but of course the pid mentioned in `var/run/roudi.pid` is not correct from perspective of the non-RouDi container. I wonder whether this is the reason for the iceoryx application to not find RouDi? Maybe you have an Idea where to look at?

**Comment by elBoberido** [comment]
The applications register via a posix message queue, so this also needs to be mapped to the docker container.
I think @dkroenke has already done something similar

**Comment by jeising** [comment]
I also mounted `/dev/mqueue/` but this is not sufficient yet.

**Comment by jeising** [comment]
:man_facepalming: 
`--ipc host` does the trick. Forget all the funny mounting.

**Comment by jeising** [comment]
This is working fine. I would close this issue.
