### ISSUE TITLE
compile error with clang

### ISSUE THREAD

**Issue by elBoberido** [eclipse/iceoryx#43]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
clang 9

**Observed result or behaviour:**
- the TOML support doesn't work
- posh is not compiling
- the tests are not compiling

**Expected result or behaviour:**
compile iceoryx with clang 9

**Conditions where it occurred / Performed steps:**
complile iceoryx with clang 9

**Comment by michael-poehnl** [comment]
@elBoberido  So we can close this one now?

**Comment by elBoberido** [comment]
yes, I can build iceoryx with clang 9
