### ISSUE TITLE
string with fixed but compile-time configurable capacity

### ISSUE THREAD

**Issue by FerdinandSpitzschnueffler** [eclipse/iceoryx#53]
## Brief feature description

For a fine grained control of the size of strings in different parts of the project, a string with a fixed but compile-time configurable capacity is required. Furthermore, throwing exceptions or using heap is forbidden.

## Detailed information

This can be achieved by integrating the new cxx::string which uses a template parameter for its capacity. It also provides a std::string compatible comparison which compares past the first '\0'.

**Comment by mossmaurice** [comment]
Part of #59 and #70
