### ISSUE TITLE
iceoryx to cyclonedds gateway

### ISSUE THREAD

**Issue by ithier** [eclipse/iceoryx#64]
## Brief feature description
A gateway to bridge between iceoryx and systems using the cyclonedds stack.
This component handles the communication in the iceoryx -> dds direction.

## Detailed information
Should allow for data published in iceoryx systems to be received remotely via DDS.
This component is a building towards achieving internode communication between iceoryx systems.

**Comment by michael-poehnl** [comment]
@ithier Will this be based on the C or the upcoming C++ API of Cyclone DDS
@joespeed FYI

**Comment by ithier** [comment]
This initial implementation will be based on this C++ API to cyclonedds: https://github.com/ThijsSassen/cdds-cxx
