### ISSUE TITLE
Can't compile due to missing CPPTOML

### ISSUE THREAD

**Issue by Karsten1987** [eclipse/iceoryx#67]
## Required information

**Operating system:**
OSX

**Compiler version:**
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix

**Observed result or behavior:**
Can't compile workspace with `colcon` due to missing `cpptoml` dependency.

**Expected result or behavior:**
A clean `colcon` compilation where all dependencies are successfully resolved and I can use ROS2.

**Conditions where it occurred / Performed steps:**
`colcon build --packages-up-to iceoryx_posh`.

**Comment by blackliner** [comment]
Git bisected it:
a5bc52a6a1a14eb0a2ddd5b3c20fb3398f08a002 is the first bad commit

**Comment by blackliner** [comment]
Manual bisect, 2648bf6530b97e7f7e27daf9f8e6b082a3a50403 is the last good one

**Comment by michael-poehnl** [comment]
Yes @blackliner. #68 will fix it. We need adaptations for colcon build
