### ISSUE TITLE
Copy and paste typo in a_typed_api.hpp

### ISSUE THREAD

**Issue by rex-schilasky** [eclipse/iceoryx#7]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.4.0

**Observed result or behaviour:**
Copy and paste issue in a_typed_api.hpp ?

https://github.com/eclipse/iceoryx/blob/ea4018918f3752f8c9ee5e48fb08626bbfc5a39e/iceoryx_examples/icedelivery/a_typed_api.hpp#L123

Shouldn't it be _TopicType_ instead _CounterTopic_  ?

**Comment by michael-poehnl** [comment]
Yep

**Comment by michael-poehnl** [comment]
Fixed with #18
