### ISSUE TITLE
Remove const_cast wherever possible

### ISSUE THREAD

**Issue by dkroenke** [eclipse/iceoryx#76]
**Brief feature description:** 
Check the necessity of all occurring const_casts and remove them if possible.

**Detailed information:** 
To check/improve const correctness in iceoryx we should take a look at all occurring const_casts and refactor them if possible.

**Comment by elBoberido** [comment]
in some places its just like
```
int foo() const;
int foo();
```
where `foo` calls `foo() const`
this could probably be fixed by 
```
int foo() const;
int foo();
private:
int foo_impl() const;
```
then `foo()` and `foo() const` can just call `foo_impl() const`
