### ISSUE TITLE
Reduce default memory consumption with config and mempools 

### ISSUE THREAD

**Issue by budrus** [eclipse/iceoryx#78]
## Brief feature description

The current defaults for compile time configuration and mempools are quite high. Better have reasonable defaults and let people increase the values if needed

## Detailed information

With the current default configuration we need ~200 MB for the internal data structures and the default memory pools have ~ 600 MB. This is a challenge on systems which only have some hundred MBs of RAM left. Beginners could be confused and get out of memory errors on RouDi startup. We support 4096 publishers and subscribers with the default config. Because of max size allocation with fixed size containers this blows up the memory. For most users a lower number is sufficient. The mempools can be easily configured with the config file now, so having the large default does not make sense IMHO

**Comment by mossmaurice** [comment]
Reopening, to make `RouDiEnvironment` more configurable and adapt TOML files.
