### ISSUE TITLE
lock free mpmc queue

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse/iceoryx#80]
## Brief feature description

Create a lock-free multi producer multi consumer queue to be used in multicast scenarios (as in e.g. ROS) and for internal control flow.

## Detailed information

Properties:
1) lock-free and hence thread-safe
2) usable by an arbitrary number of multiple producers and consumers concurrently
3) no dynamic memory for safety reasons (uses its own memory buffer, determined at compile time, later configured during initialization)
4) robust -when an application terminates unexpectedly while using the queue 
the middleware daemon has to stay operational
5) suited to be placed in shared memory
6) low performance overhead when there is little contention

**Comment by budrus** [comment]
is needed for #25
