### ISSUE TITLE
ASIL-D compliance 

### ISSUE THREAD

**Issue by ShawnSchaerer** [eclipse/iceoryx#83]
Is there any updates on ASIL-D compliance and how do you plan on getting there?
We are looking at using Iceoryx in a commercial product and would like to understand the roadmap for safety.

**Comment by budrus** [comment]
Hi @ShawnSchaerer 
Nice to here. The safety roadmap is linked to the roadmaps of our customers. Current plan is to have an ASIL B in 2021 and an ASIL D in 2022 or 2023. In the end It is a matter of prioritization.  
There are two dimensions and the question of their balance
a) Having more features and more platforms: e.g. #27 and #33. 
b) Having the focus on production readiness and safety level X for a specific feature set and platform (like pub/sub on QNX)

a) is important for topics like becoming ROS2 tier 1. On the other side, ASIL compliance will not target all operating systems and has some other constraints. 

The safety topic has also two dimensions
a) how iceoryx is developed
b) how iceoryx is used  
  
a) is a question of development process, testing, etc. We have the know how for this. Here the challenge is that it is not easy to fulfill everything with just a github project. So we have some extra work with established internal processes and tools. One thing that we provide soon online are the QAC++ warning reports, here we are just setting up things with Perforce. The code base that we will have on ASIL level is currently restricted to QNX as OS.

b) If you want to use iceoryx in a specific environment, a safety manual is needed that guides you and it must be released/validated for this environment. Here we are talking about which compiler with version and flags you are using, on which OS and version and on which hardware.  You have to get in touch with us for these questions. Only the code is not the full answer to the ASIL question

**Comment by ShawnSchaerer** [comment]
@budrus Thanks for the repsonce.
I will email to discuss in more detail, but I understand what you are saying.  
We are just making sure that their is a road map for ASIL certification or that it will be possible later.

Our system is running on QNX so there should be a way forward for us.
